### ISSUE TITLE
A lot of spdlog errors

### ISSUE THREAD

**Issue by eoan-ermine** [userver-framework/pg_service_template#10]
1. make docker-start-service -> Успешный запуск сервиса
2. Отключить сервис (Ctrl-C, for example)
3. Внести изменения, из-за которых third-party/spdlog надо будет перекомпилироваться
4. make docker-start-service -> См. [log.txt](https://github.com/userver-framework/pg_service_template/files/9229579/log.txt)

**Comment by eoan-ermine** [comment]
Это фиксится удалением папки `build_release`: после этого `make docker-start-service` успешно отрабатывает, но каждый раз удалять `build_release` по очевидным причинам неудобно.

**Comment by eoan-ermine** [comment]
Полная репродукция:

1. `make docker-start-service`, Ctrl-C -> [log.txt](https://github.com/userver-framework/pg_service_template/files/9229588/log.txt)
2. Внесены изменения в CMakeLists.txt
1. `make docker-start-service` -> [log.txt](https://github.com/userver-framework/pg_service_template/files/9229590/log.txt)

**Comment by eoan-ermine** [comment]
Выглядит так, что все docker- команды к этому приводят.

**Comment by apolukhin** [comment]
Хм... Кажется что в Makefile где-то не хватает зависимостей... Поищем

**Comment by alexiprof** [comment]
такое ощущение, что пытались пересобрать cmake потом руками и он неправильно пути проставил,
попробуйте удалить дирректорию `third_party/userver/third_party/spdlog`

**Comment by apolukhin** [comment]
Мы уничтожили зависимость на spdlog, проблема решена :)
