### ISSUE TITLE
Возможно ли менять порт в шаблоне?

### ISSUE THREAD

**Issue by Andromeda-SRT** [userver-framework/pg_service_template#25]
Пробывал сменить порт в файлах конфигурации таких как: 
```
config_vars.yaml; 
static_config.yaml.in; 
static_config.yaml; 
config_vars_testing.yaml 
```
Расположенных в директории ./configs a так же 
```
config_vars.yaml
```
в директории /usr/local/etc/.../config_vars.yaml

Но после ввода 
```
make build-debug 
```
или 
```
make start-... 
```
ничего не меняется, запуск всё так же происходит на порт 8080

**Comment by apolukhin** [comment]
Если вы запускаете через тестсьют (make start или make test), то тестсьют автоматически подменяет порт на свободный в фикстуре userver_config_base https://userver.tech/dc/db7/group__userver__testsuite__fixtures.html#userver_config_base

Чтобы по честному запустить, без тестсьюта, нужно запустить бинарник вручную, наподобие `./samples/hello_service/userver-samples-hello_service -c </path/to/static_config.yaml> `

**Comment by Andromeda-SRT** [comment]
Спасибо получилось!
1. Добавил запрашиваемый конфиг в директорию /usr/local/etc/My_Service_Name/: 
```
sudo cp ../configs/dynamic_config_fallback.json /usr/local/etc/My_Service_Name/
```
2. Из папки ./build_release запустил бинарник:
```
./My_Service_Name -c ../configs/static_config.yaml
```
Порт сменился.
