### ISSUE TITLE
Impossible build on mac with default make

### ISSUE THREAD

**Issue by electfreak** [userver-framework/pg_service_template#30]
```shell
make service-start-debug
```
Просто не работает на маке. Внутри контейнера не находится make, потому что на маке он лежит по пути 
`/Library/Developer/CommandLineTools/usr/bin/make`
Подозреваю, что сборка на машине с линуксом работает, потому что чаще всего совпадает путь до make с контейнером (`/usr/bin/make`). 
В чем цель использования `$(MAKE)` в Makefile вместо просто make или `/usr/bin/make` ? Я думаю, что если путь до make на машине отличается от пути в контейнере, то работать не будет. Я понимаю, что `$(MAKE)` можно использовать например для проброса параметров в рекурсивные запуски, но все равно не стоит же пробрасывать путь и параметры того make, который используется на машине, потому что, как я сказал, он может отличаться от make в образе.

**Comment by apolukhin** [comment]
Поправили в https://github.com/userver-framework/pg_service_template/pull/41

Пожалуйста, переоткройте PR или заведите новый, если вдоуг не помогло

Большое спасибо за багрепорт!
